{
  "type": "record",
  "name": "CustomerBalance",
  "fields": [
    {
      "name": "customer_number",
      "type": {
        "type": "string",
        "arg.properties": {
          "options": [
            "123456789",
            "123456790",
            "123456791",
            "123456792",
            "123456793",
            "123456794",
            "123456795",
            "123456796",
            "123456797",
            "123456798",
            "123456799",
            "123456800"
          ]
        }
      }
    },
    {
      "name": "balance",
      "type": {
        "type": "double",
        "arg.properties": {
          "range": {
            "min": 25000.000,
            "max": 30000.000
          }
        }
      }
    }
  ]
}
